### ISSUE TITLE
IPtables in Vagrant setup -  Worker

### ISSUE THREAD

**Issue by DailyAlice** [tinkerbell/tinkerbell.org#112]
There was a request for docs surrounding iptables on a Worker post-Vagrant set up.

Need to follow-up with @Cbkhare, @gianarb, or @dan to get the details.

**Comment by thebsdbox** [comment]
The issue that we face is that whilst a machine/laptop may be internet facing, the virtual machines created by Vagrant are not.

```
   +--------------+
   |   Internet   |
   +------+-------+
          |
+--------------------------------------------+
|         |                                  |
|  +------+-----+       +--------------+     |
|  |    eth0    |       |  Tinkerbell  |     |
|  +------------+       +-+------------+     |
|                         |                  |
+--------------------------------------------+
                          |
                    +-----v-----+
                    |    VM1    |
                    +-----------+
```

In order to provide this functionality to these created virtual machines we need to use `iptables` to allow `ip_forwarding` and network address translation from the network traffic of `VM1` to traverse `eth0`

export main=<public_ip_iface>
export vagrant=<tinkerbell_ip_iface> 
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -A FORWARD -i $vagrant -o $main -j ACCEPT
iptables -A FORWARD -i $main -o $vagrant -m state --state ESTABLISHED,RELATED \
         -j ACCEPT
iptables -t nat -A POSTROUTING -o $vagrant -j MASQUERADE

```
   +--------------+
   |   Internet   |
   +------+-------+
          |
+----------------------------------------------------+
|         |                                          |
|  +------+---+---------------------->+------------+ |
|  |    eth0  |       iptables        | Tinkerbell | |
|  +----------+<----------------------+--------+---+ |
|                                              |     |
+----------------------------------------------------+
                                               |
                                           +---v---+
                                           |  VM1  |
                                           +-------+
```

**Comment by DailyAlice** [comment]
@thebsdbox does this issue affect both the Provisioner and the Worker? I think this originally discussed in context of letting a Worker see the Internet, but if it does also affect the Provisioner are there any cases where you would want to run the commands there too?

**Comment by DailyAlice** [comment]
Other thoughts - I can just drop in this content at the end of the Vagrant set up doc, but is there any context on why someone would want or need to have the Worker see the Internet at this point? @thebsdbox
