### ISSUE TITLE
Update Tinkerbell favicon

### ISSUE THREAD

**Issue by mrmrcoleman** [tinkerbell/tinkerbell.org#170]
tinkerbell.org has a favicon. docs.tinkerbell.org does not have a favicon.

I would like docs.tinkerbell.org to have the same favicon as tinkerbell.org.

## Expected Behaviour

See above

## Current Behaviour

See above

## Possible Solution

See above

## Steps to Reproduce (for bugs)

1. Open tinkerbell.org in a browser
2. Open docs.tinkerbell.org in a browser

## Context

See above

## Your Environment

n/a

**Comment by mrmrcoleman** [comment]
@ronggur Can you assist with the above?

**Comment by felixwidjaja** [comment]
I guess this is for `docs.` right? I made the new issue [here](https://github.com/tinkerbell/tinkerbell-docs/issues/33).
Since we're already here, can @geriadam update using the better one? (transparent, also same version as attached [here](https://github.com/tinkerbell/tinkerbell-docs/issues/33))
Thanks.

[16dfade641c40f1233385cc5b81b83ef.ico.zip](https://github.com/tinkerbell/tinkerbell.org/files/5651139/16dfade641c40f1233385cc5b81b83ef.ico.zip)

**Comment by mrmrcoleman** [comment]
Yep, this is for docs "docs.tinkerbell.org does not have a favicon."
